# NumPy
NumPy bilimsel hesaplamalar yapmak için pratik bir pakettir.

In [ ]:
import numpy as np

 ## Array Oluşturmak

In [12]:
a = [1, 2, 3, 4, 5]

In [13]:
type(a)

list

In [18]:
b = list(range(6, 11))
b

[6, 7, 8, 9, 10]

In [19]:
a + b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

np.array()

In [20]:
a1D = np.array(a)

In [21]:
print(a1D)

[1 2 3 4 5]


In [22]:
b1D = np.array(b)

In [23]:
print(b1D)

[ 6  7  8  9 10]


In [24]:
type(a1D)

numpy.ndarray

In [25]:
a1D + b1D

array([ 7,  9, 11, 13, 15])

In [26]:
a, b

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])

In [27]:
[a, b]

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [28]:
a2D = np.array([a, b])

In [29]:
print(a2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [30]:
a2D * a2D

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

## 1D Array oluşturma fonksiyonları

In [32]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [37]:
list(range(5, 10, 2))

[5, 7, 9]

In [38]:
np.arange(5, 10, 2)

array([5, 7, 9])

## np.linspace

In [ ]:
np.linspace()

In [39]:
np.linspace(0, 49)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [40]:
np.linspace(5, 50, num=21)

array([ 5.  ,  7.25,  9.5 , 11.75, 14.  , 16.25, 18.5 , 20.75, 23.  ,
       25.25, 27.5 , 29.75, 32.  , 34.25, 36.5 , 38.75, 41.  , 43.25,
       45.5 , 47.75, 50.  ])

## 2D Array oluşturma fonksiyonları

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.eye(6, dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

## np.zeros

In [43]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [44]:
np.zeros((2, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [45]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
np.zeros((2, 3, 1))

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [47]:
np.zeros(shape=(2, 3), dtype=int) + 1

array([[1, 1, 1],
       [1, 1, 1]])

## Numpy Array'leri Çoğaltma, Birleştirme ve Değiştirme

In [48]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [49]:
b = a

In [50]:
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [51]:
b += 1

In [52]:
print(b)

[ 1  2  3  4  5  6  7  8  9 10]


In [53]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [54]:
id(a)

2167463939504

In [55]:
id(b)

2167463939504

In [56]:
c = a.copy()

In [57]:
id(c)

2167463944592

In [58]:
c += 1

In [59]:
print(c)

[ 2  3  4  5  6  7  8  9 10 11]


In [60]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


### np.vstack, np.hstack

In [63]:
a = np.array(range(1, 5))
b = np.array(range(5, 9))
c = np.array(range(9, 13))
d = np.array(range(13, 17))

In [64]:
print(a)
print(b)
print(c)
print(d)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [65]:
np.vstack((a, b, c, d))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [66]:
np.hstack((a, b, c, d))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

## np.diag

In [67]:
np.diag((1, 2, 5, 7, 9))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 9]])

In [68]:
np.ones((5, 7), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

## Random

In [70]:
np.random.rand()

0.76715063801052

In [71]:
np.random.rand(3)

array([0.93759615, 0.83005671, 0.95400823])

In [72]:
np.random.rand(5, 4)

array([[0.92094985, 0.93060675, 0.63888276, 0.5102609 ],
       [0.62394574, 0.54961604, 0.69788159, 0.75170848],
       [0.92150458, 0.09240907, 0.32756577, 0.35364474],
       [0.82158606, 0.34798247, 0.2507341 , 0.63227258],
       [0.58816959, 0.25555831, 0.50333039, 0.41396815]])

In [74]:
np.random.rand(3, 4)*10

array([[5.11788775, 1.98558194, 4.62365524, 7.93866122],
       [4.45859992, 1.61474025, 8.73462355, 8.44249496],
       [4.64243165, 0.93581851, 4.59705901, 6.27714607]])

## randn

In [76]:
np.random.randn()

-2.182525175215498

In [77]:
big_arr = np.random.randn(100000)

In [78]:
type(big_arr)

numpy.ndarray

In [79]:
len(big_arr)

100000

In [80]:
big_arr.mean()

0.002635240123999853

In [81]:
big_arr.std()

1.0040324322842422

In [82]:
big_arr.argmax()

47860

## seed

In [84]:
np.random.seed(101)
np.random.randn()

2.706849839399938

## arrayleri yeniden şekillendirme

In [85]:
arr = np.arange(1, 17)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [86]:
arr.reshape(4, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## indeksleme ve dilimleme

In [88]:
arr = np.arange(0,16)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [89]:
arr[2]

2

In [90]:
arr = np.arange(0, 35, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]


In [91]:
arr[6]

12

In [93]:
arr = arr.reshape(3, 3, 2)
print(arr)

[[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [16 18]
  [20 22]]

 [[24 26]
  [28 30]
  [32 34]]]


In [94]:
arr[1]

array([[12, 14],
       [16, 18],
       [20, 22]])

In [95]:
arr[1][1]

array([16, 18])

In [96]:
arr[1][1][1]

18

In [97]:
arr[0][1][0]

4

In [98]:
arr[-1]

array([[24, 26],
       [28, 30],
       [32, 34]])

### Slicing

In [102]:
arr =np.arange(10, 35)


In [103]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34])

In [104]:
arr[3:8]

array([13, 14, 15, 16, 17])

In [105]:
arr[-6:-2]

array([29, 30, 31, 32])

In [106]:
len(arr)

25

In [107]:
arr = arr.reshape(5, 5)

In [108]:
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [109]:
arr[1:3]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [110]:
arr[1:3][1:3]

array([[20, 21, 22, 23, 24]])

In [111]:
arr[1:3,1:3]

array([[16, 17],
       [21, 22]])

In [115]:
arr[2:, 3:]

array([[23, 24],
       [28, 29],
       [33, 34]])

## Koşullu filtreleme

In [117]:
np.random.seed(51)
arr = np.random.randint(0, 100, size=50)
print(arr)

[57 96 73 69 16 21 94 52 37 37 60 94 28 84 36 35 27 28 42 10  6 25 33 77
 39 48 24 40 54 77 28 69 57 18 63 75 67 94 87  7 67 91 61 34 53 30 55 17
 67  8]


In [119]:
bool_arr = arr > 50
print(bool_arr)

[ True  True  True  True False False  True  True False False  True  True
 False  True False False False False False False False False False  True
 False False False False  True  True False  True  True False  True  True
  True  True  True False  True  True  True False  True False  True False
  True False]


In [120]:
arr[bool_arr]

array([57, 96, 73, 69, 94, 52, 60, 94, 84, 77, 54, 77, 69, 57, 63, 75, 67,
       94, 87, 67, 91, 61, 53, 55, 67])

In [121]:
arr[arr > 50]

array([57, 96, 73, 69, 94, 52, 60, 94, 84, 77, 54, 77, 69, 57, 63, 75, 67,
       94, 87, 67, 91, 61, 53, 55, 67])

In [122]:
arr2 = np.array([1, 3, 4, 7, 8, 9])
bool_arr2 = np.array([False, False, True, False, True, False])

In [123]:
len(arr2)

6

In [124]:
len(bool_arr2)

6

In [125]:
arr2[bool_arr2]

array([4, 8])

In [127]:
np.random.seed(51)
arr3 = np.random.randint(125, 675, 100)
print(arr3)

[182 610 653 561 486 674 153 288 153 551 131 542 586 625 429 149 179 153
 316 200 377 475 596 344 415 562 283 180 654 242 566 266 212 194 366 177
 174 128 403 468 576 634 629 443 544 560 220 602 465 634 433 299 369 172
 209 506 603 484 358 297 565 369 486 549 476 137 580 292 481 562 166 241
 200 208 310 600 127 297 172 533 605 387 414 642 654 279 487 410 326 291
 625 539 386 451 282 396 306 624 495 585]


In [130]:
arr3[(arr3 > 250) & (arr3 < 400)]

array([288, 316, 377, 344, 283, 266, 366, 299, 369, 358, 297, 369, 292,
       310, 297, 387, 279, 326, 291, 386, 282, 396, 306])

In [133]:
np.random.seed(51)
arr3 = np.random.randint(1, 100, 50)
print(arr3)

[58 97 74 70 17 22 95 53 38 38 61 95 29 85 37 36 28 29 43 11  7 26 34 78
 40 49 25 41 55 78 29 70 58 19 64 76 68 95 88  8 68 92 62 35 54 31 56 18
 68  9]


In [134]:
arr3[arr3 > 25]

array([58, 97, 74, 70, 95, 53, 38, 38, 61, 95, 29, 85, 37, 36, 28, 29, 43,
       26, 34, 78, 40, 49, 41, 55, 78, 29, 70, 58, 64, 76, 68, 95, 88, 68,
       92, 62, 35, 54, 31, 56, 68])

In [140]:
arr3[arr3 > 25].sum()

2381

In [138]:
arr3.ndarray.sum

AttributeError: 'numpy.ndarray' object has no attribute 'ndarray'

In [141]:
arr3[arr3 > 25].mean()

58.073170731707314

In [142]:
arr3[arr3 > 25].std()

21.76413501321129

## NumPy Operations

### Arithmetic Operations

In [143]:
a = np.array([4, 5, 6])
b = np.array([1, 2, 3])

In [144]:
arr

array([57, 96, 73, 69, 16, 21, 94, 52, 37, 37, 60, 94, 28, 84, 36, 35, 27,
       28, 42, 10,  6, 25, 33, 77, 39, 48, 24, 40, 54, 77, 28, 69, 57, 18,
       63, 75, 67, 94, 87,  7, 67, 91, 61, 34, 53, 30, 55, 17, 67,  8])

In [145]:
arr += 1

In [146]:
print(arr)

[58 97 74 70 17 22 95 53 38 38 61 95 29 85 37 36 28 29 43 11  7 26 34 78
 40 49 25 41 55 78 29 70 58 19 64 76 68 95 88  8 68 92 62 35 54 31 56 18
 68  9]


In [147]:
arr.sort()

In [148]:
arr

array([ 7,  8,  9, 11, 17, 18, 19, 22, 25, 26, 28, 29, 29, 29, 31, 34, 35,
       36, 37, 38, 38, 40, 41, 43, 49, 53, 54, 55, 56, 58, 58, 61, 62, 64,
       68, 68, 68, 70, 70, 74, 76, 78, 78, 85, 88, 92, 95, 95, 95, 97])

In [149]:
np.mean(arr)

50.34

In [150]:
arr.mean()

50.34

In [152]:
np.median(arr)

51.0